### PR TITLE
Fix GitHub url for a private repository in Flex endpoint

### PR DESCRIPTION
**Pull request by b-durand**
## Problem
https://raw.githubusercontent.com doesn't work for a private repo with the OAuth token used by composer. We need to hit https://api.github.com.

## Solution
Add a new flag `--private` to switch url

### CODE REVIEW

**Comment by aivus** [comment]
Hey @b-durand 

Additional change is required in
https://github.com/symfony-tools/recipes-checker/blob/bf7314cbe644868e1b16054fb41837a28bf8cdab/src/ListUnpatchedPackagesCommand.php#L35


We need to pass header to property receive diff
```
        $diff = $client->request('GET', $data['pull_request']['url'],
            [
                'auth_bearer' => $input->getArgument('github_token'),
                'headers' => ['Accept' => 'application/vnd.github.v3.diff'],
            ]
        )->getContent();
```

**Comment by nicolas-grekas** [comment]
Wouldn't https://github.com/symfony/flex/pull/842 be a better fix for private repos? I'd prefer not adding one more flag if possible.

**Comment by b-durand** [comment]
@nicolas-grekas what do you suggest as solution? `api.github.com` or `raw.githubusercontent.com`? The desired way is unclear. Why symfony/flex#842 is closed instead of merged? I'm up for a PR here or in Flex.

How many uses Symfony Flex without a GitHub OAuth token? Do you have a kpi to check the impact of this commit e0bdb0aa9e90523c627c27e25d25cf3362c6a6c3?

Or `--private` enforce `--contrib` by default and we have only one flag 😸

**Comment by nicolas-grekas** [comment]
Can you please try with the latest release of flex? I merged https://github.com/symfony/flex/pull/842. Maybe this PR is not needed anymore now?

**Comment by aivus** [comment]
I just checked changes from https://github.com/symfony/flex/pull/842 on my test private repo and they are looks good.
I was able to use checker from symfony-tools without modifications.

At the same time we need https://github.com/symfony-tools/recipes-checker/pull/8 to properly generate diff of packages.

> Why https://github.com/symfony/flex/pull/842 is closed instead of merged?

@b-durand I closed it because there were some concerns from other Symfony member and I decided to go with modifications of `recipes-checker` instead of modifications flex itself.

**Comment by nicolas-grekas** [comment]
Thank you both for your help pushing this forward.

**Pull request closed without merging**
